[env]
GOEXPERIMENT = "jsonv2"
CGO_ENABLED = 0

[tools]
go = "latest"
golangci-lint = "latest"

[tasks.build]
run = "go build ./cmd/notman"

[tasks."build:image"]
depends = "build"
run = "docker build . -f Containerfile -t notman:local"

[tasks.test]
depends = "build:image"
dir = "test"
run = "go test -v notmat_test.go"
