name: Build and Publish Image
description: Build and Publish Container image
inputs:
  github-token:
    required: true
    description: Github Token

runs:
  using: composite
  steps:
    - name: Generate Image Tags
      id: tags
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          TAGS="pr-${{ github.event.pull_request.number }} ${{ github.event.pull_request.head.sha }}"
        elif [ "${{ github.event_name }}" == "push" ] || [ "${{ github.ref_name }}" == "main" ]; then
          TAGS="latest ${{ github.sha }}"
        fi
        echo "tags=$TAGS" >> "$GITHUB_OUTPUT"

    - name: Install qemu dependency
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Build Multi-arch Image
      id: build
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ github.repository }}
        tags: ${{ steps.tags.outputs.tags }}
        archs: amd64, arm64
        containerfiles: |
          ./Containerfile

    - uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: github_workflow
        password: ${{ inputs.github-token }}

    - name: Push Images
      id: push
      uses: redhat-actions/push-to-registry@v2
      with:
        registry: ${{ env.REGISTRY }}
        image: ${{ steps.build.outputs.image }}
        tags: ${{ steps.tags.outputs.tags }}
